name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22
      - name: Build geoip
        env:
          IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
        run: go run -v .
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: geoip.db
          path: geoip.db